name = "QSFit"
uuid = "fea25315-b951-4667-83c9-50e53efab241"
authors = ["Giorgio Calderone <giorgio.calderone@gmail.com>"]
version = "0.1.0"

[deps]
CMPFit = "a5944310-3432-5d93-8bb2-e3b5eb62a58f"
Cosmology = "76746363-e552-5dba-9a5a-cef6fa9cc5ab"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
FITSIO = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"
GFit = "ac42e6ba-c0bf-4fcf-827d-deea44b16255"
GFitViewer = "5d93b50e-5cc7-4feb-a740-ec85257caa01"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAstro = "6112ee07-acf9-5e0f-b108-d242c714bf9f"
